title: ReplatformTech
#email: your-email@mail.com
#tel: (+1) 111-111-1111
description: Replatform Technologies, LLC specializes in migrating mission critical mainframe applications to low-cost, high-performance platforms.
url: https://replatformtech.github.io/ # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

plugins:
  - github-pages

sass:
  sass_dir: _scss
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
